typography_spectrum: 0.23747709416784346
color:
  brandColors:
    - '#ffffff'
    - '#c557a0'
    - '#f7e8f6'
    - '#d688b4'
    - '#e7b4d9'
  brandStrength: 0.5083829897921532
  lightness: 0.6405037853401154
  saturation: 0.051777559565380216
  rhythmicContrast: 0.22792402980849147
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3948
analytics:
  google: null
  facebook: null
  twitter: null
name: Mind Baby Spirit
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Mind Baby Spirit
purpose: []
